### PR TITLE
fix: support http_proxy & https_proxy environment variables

### PR DESCRIPTION
**Pull request by yugasun**
## What has been implemented?

Closes #XXXXX

## Steps to verify

- Run X
- ...

## Todos:

- [x] Write tests
- [x] Write / update documentation
- [x] Run Prettier

### CODE REVIEW

**Review by zongUMR — APPROVED** [review]

**Review by zongUMR — CHANGES_REQUESTED** [review]
We should update the `version`

**Comment by yugasun** [comment]
This is a small fix, so no need to publish a version, maybe merged and published with other PR

**Review by zongUMR — APPROVED** [review]

**Comment by zongUMR** [comment]
@yugasun If there's no problem, can you merge this PR?

**Comment by yugasun** [comment]
@zongUMR I don't have the permission to merge.

**Comment by zongUMR** [comment]
> @zongUMR I don't have the permission to merge.

OK, let me merge it and it will release the `canary` CLI version, then you can take a test

**Comment by zongUMR** [comment]
@yugasun CLI canary released, you can test it now.

**Pull request merged**
