### PR TITLE
fix: resolve content from env with strong type

### PR DESCRIPTION
**Pull request by zongUMR**
## What has been implemented?

Closes https://github.com/serverless/components/issues/796

## Steps to verify

This code will get content from `process.env` and convert them, return a new object with strong type.

`resolveVariables` will insert `number, string, boolean, null, undefined` content back to yaml when it has `${env:xxx}`

## Todos:

- [ ] Write tests
- [ ] Write / update documentation
- [ ] Run Prettier

### CODE REVIEW

**Review by medikoo — COMMENTED** [review]
@zongUMR what exactly use case we're trying to address here?

Technically by _nature_ `process.env` vars are strings, and it doesn't feel as a right move try to imply a generic mechanism to try handle that differently.

Ideally if specific typing is needed for some specific case, then best is to solve it when addressing given case specifically.

**Comment by zongUMR** [comment]
@medikoo If an user input `export test=1 && sis deploy` and the config file has `${env:test}` here, then the old code will insert the `test` var is a string one, but user wants a number one, and when we send this var to the Tencent API, the API will validate the type of value, it needs a number as well, so we need to convert the real type of this value

**Comment by medikoo** [comment]
> @medikoo If an user input export test=1 && sis deploy and the config file has ${env:test} here, then the old code will insert the test var is a string one. 

imo it's definitely an expected behavior.

If intention is to interpolate it to _number_ in some specific case, then I believe best if we introduce some type interpolation instructions at config var resolution level, e.g. in Framework we have such thing to e.g. interpolate booleans: https://www.serverless.com/framework/docs/providers/aws/guide/variables/#read-string-variable-values-as-boolean-values.

In components we may propose some simpler notation that will allow to interpolate to more types.

Note that trying to convert _string_ values unconditionally to some other type just by reasoning on their content may introduce a lot of issues, e.g. what if I unconditionally need a `"1"` or `"null"` string?

**Comment by yugasun** [comment]
@medikoo Providing modify function for `${modifyFunc(env:xxx)}` is really a good method. Maybe we can add below function for most cases:

```
strToBool
strToNum
numToStr
```

**Comment by medikoo** [comment]
@yugasun sounds good to me, @eahefnawy what do you think?

**Comment by zongUMR** [comment]
That's good,  I will remove the `convert` code and only remain the `readme` changes.

**Pull request closed without merging**
