### PR TITLE
feature: friendly logging for devOps

### LINKED ISSUE #834: Logging suitable for CI mode must be supported.
# Description
When i run `npx serverless --debug`, a lot of meaningless logs are output. This makes debugging very difficult.

Screen Shot 2020-11-03 at 5 22 17 PM

In CI mode (non-interactive mode), Repeated `Deploying...` logs should not be output.

Many other packages use the `--ci` option or an environment variable such as `CI=true`.

### LINKED ISSUE #945: [feat] devOps friendly output format (JSON, YAML)
# Description
It should be a common use case to integrate Serverless Component into CI/CD pipelines, where outputs are usually parsed with scripts to further trigger other pipelines.

It would be really helpful if `serverless deploy` and `serverless info` allows an option for output formats, such as `serverless deploy --format json`.

This option should implies skipping the deploying TUI progress bar, which also solves #834.

### PR DESCRIPTION
**Pull request by KimPinot**
## What has been implemented?

The Pull Request adds features related to overall support for CI/CD and devOps.

Closes #834
## Steps to verify

- [x] disable persistent status bar in the CLI 
- [x] Add the ability to automatically detect environment variables and apply CI mode.

~- [ ] Add output for `serverless deploy` and `serverless info` commands~

## Todos:

- [x] Write / update documentation
- [x] Run Prettier

### CODE REVIEW

**Comment by KimPinot** [comment]
@ole3021 @medikoo Hello! May I ask you to review this PR?

**Comment by ole3021** [comment]
@eahefnawy  @medikoo  could you please check this PR and follow up. this will add a new arg `--ci` to keep the log in ci tidy.  i dont think `--ci` is a good name here, as we like to achieve is to make the terminal logs as simple as possible (with just deploy results)

**Comment by KimPinot** [comment]
Thank you for your feedback. @ole3021 
I'm thinking of these names right now, so could you choose between them or put them on the thread if you have any good ideas?

- `--tidy-logs`
- `--clean`
- `--reduce`

**Review by medikoo — CHANGES_REQUESTED** [review]
I think best solution would be to rely on feature detection, and do not introduce any option at all.

Animated progress definitely should not be shown in non TTY terminals (and by nature CI runs happen in those).

Therefore I would simply not show progress if `!process.stdin.isTTY`. https://nodejs.org/api/tty.html#tty_tty

**Review by medikoo — COMMENTED** [review]
@KimPinot thanks for update.

Still I think more natural would be to have `_isTTY` and not `_isNotTTY` (?)

**Comment by KimPinot** [comment]
I thought it was mostly used when it wasn't isTTY, so I wrote it in negative form, but I guess it wasn't. 😅

**Review by medikoo — APPROVED** [review]
Thank you @KimPinot! Looks good to me 👍

**Comment by ole3021** [comment]
@medikoo  are we good to process this PR?

**Comment by KimPinot** [comment]
@ole3021 Yes. The features scheduled for #945 would like to work with a different PR.

**Comment by KimPinot** [comment]
@ole3021 Can you run Lint & Formatting workflows? I forgot run prettier at CLI.js :<

**Comment by herrlegno** [comment]
Will this be merged at some point? so this [workaround](https://github.com/serverless-nextjs/serverless-next.js/pull/1658) won't be necessary?

Thank you.

**Comment by KimPinot** [comment]
> Will this be merged at some point? so this [workaround](https://github.com/serverless-nextjs/serverless-next.js/pull/1658) won't be necessary?
> 
> 
> 
> Thank you.

Perhaps the form of PR you mentioned will be more helpful in addressing this goal!
I think we need to close the issue. Thank you for pointing it out. ❤️

**Pull request closed without merging**
