### PR TITLE
Knative integration

### PR DESCRIPTION
**Pull request by pmuens**
## What has been implemented?

Adds Environment variables to integrate the new Components implementation with a Kubernetes cluster (which in turn runs Knative).

## Steps to verify

Trust me, you don't want to test this end-to-end...

## Todos:

* [x] Run Prettier

### CODE REVIEW

**Comment by pmuens** [comment]
@eahefnawy here's the PR which adds the necessary environment variables for the Kubernetes / Knative integration.

**Comment by eahefnawy** [comment]
Let me know if this is super urgent, then I can cut a release, otherwise, we'll ship this along with some other things.

**Comment by pmuens** [comment]
Thanks for merging! :+1:

> Let me know if this is super urgent, then I can cut a release, otherwise, we'll ship this along with some other things.

It seems like it's not super urgent right now. I'll let you know if this changes and we should cut a release...

**Comment by fernando-mc** [comment]
@eahefnawy @medikoo would it be possible to actually cut a release for this? I'm working on a demo today that needs it.

**Pull request merged**
