### PR TITLE
Refactor credentials handling

### PR DESCRIPTION
**Pull request by eahefnawy**
## What has been implemented?

- credentials will only be loaded from .env files
- credentials will no longer be automatically loaded from the environment
- credentials will no longer be automatically loaded from the aws credentials file in the home directory
- only if the user explicitly specified AWS_PROFILE env var in the .env file, only then we will load this profile credentials from the aws credentials file
- also fixes a bug that loaded the wrong file .env for the given stage

**Note: This is a necessary breaking change**

## Steps to verify

Deploy a component without credentials in the .env file, but with credentials in the environment or home directory. The deployment should fail.

### CODE REVIEW

**Comment by mwawrusch** [comment]
Thanks, Eslam, you are a life safer. Let's hope this gets merged soon.

**Comment by eahefnawy** [comment]
@mwawrusch you're most welcome! Thanks for reporting the issue with the .env files.

**Review by ac360 — APPROVED** [review]

**Comment by ac360** [comment]
@eahefnawy I just responded with some thoughts on an alternative solution in Slack.  This is a great idea, but I'm not sure it is clear enough for users.

In the interim, imo, we should scope this to the change @mwawrusch has been so patiently waiting for.

**Comment by mwawrusch** [comment]
Good morning, any progress on this?

**Comment by eahefnawy** [comment]
@ac360 sounds good. Closing this PR as it's no longer relevant.

@mwawrusch I've just merged your bug fix in #867. A release should be out shortly.

**Comment by eahefnawy** [comment]
The release is out 🎉 ... @mwawrusch feel free to try it out.

**Pull request closed without merging**
